/**
 * Auto-generated by AI QA Orchestrator
 * Story: STORY-1042 — Password reset via email
 * Generated by: orchestrator.py + Claude AI
 * 
 * DO NOT EDIT MANUALLY — regenerate by running orchestrator.py
 */

import { test, expect } from '@playwright/test';

test.describe('STORY-1042: Password reset via email', () => {

  // ── Happy Path Tests ────────────────────────────────────────────────────

  test('TC-001: Valid email triggers password reset email within 30 seconds', async ({ page }) => {
    await page.goto('/forgot-password');
    await page.getByLabel('Email address').fill('valid.user@example.com');
    await page.getByRole('button', { name: 'Send reset link' }).click();
    await expect(page.getByText('Reset link sent')).toBeVisible({ timeout: 30000 });
    await expect(page.getByText('Check your email')).toBeVisible();
  });

  test('TC-002: Reset link successfully opens password reset page', async ({ page }) => {
    const resetToken = 'valid-token-123';
    await page.goto(`/reset-password?token=${resetToken}`);
    await expect(page.getByRole('heading', { name: 'Reset your password' })).toBeVisible();
    await expect(page.getByLabel('New password')).toBeVisible();
    await expect(page.getByLabel('Confirm password')).toBeVisible();
  });

  test('TC-003: Valid token allows successful password reset', async ({ page }) => {
    await page.goto('/reset-password?token=valid-token-123');
    await page.getByLabel('New password').fill('NewSecurePass123!');
    await page.getByLabel('Confirm password').fill('NewSecurePass123!');
    await page.getByRole('button', { name: 'Reset password' }).click();
    await expect(page.getByText('Password reset successful')).toBeVisible();
    await expect(page).toHaveURL('/login');
  });

  // ── Edge Case Tests ─────────────────────────────────────────────────────

  test('TC-004: Reset link expires after 1 hour', async ({ page }) => {
    const expiredToken = 'expired-token-61min';
    await page.goto(`/reset-password?token=${expiredToken}`);
    await expect(page.getByText('This link has expired')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Reset password' })).toBeDisabled();
    await expect(page.getByRole('link', { name: 'Request a new link' })).toBeVisible();
  });

  test('TC-005: Reset link is single-use only', async ({ page }) => {
    const usedToken = 'already-used-token';
    await page.goto(`/reset-password?token=${usedToken}`);
    await expect(page.getByText('This link has already been used')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Reset password' })).toBeDisabled();
  });

  test('TC-006: Second reset request invalidates first link', async ({ page }) => {
    // Request first reset link
    await page.goto('/forgot-password');
    await page.getByLabel('Email address').fill('user@example.com');
    await page.getByRole('button', { name: 'Send reset link' }).click();

    // Request second reset link
    await page.goto('/forgot-password');
    await page.getByLabel('Email address').fill('user@example.com');
    await page.getByRole('button', { name: 'Send reset link' }).click();

    // First link should now be invalid
    await page.goto('/reset-password?token=first-token');
    await expect(page.getByText('This link is no longer valid')).toBeVisible();
  });

  test('TC-007: Password must meet minimum requirements', async ({ page }) => {
    await page.goto('/reset-password?token=valid-token-123');
    await page.getByLabel('New password').fill('weak');
    await page.getByLabel('Confirm password').fill('weak');
    await page.getByRole('button', { name: 'Reset password' }).click();
    await expect(page.getByText('Password must be at least 8 characters')).toBeVisible();
  });

  test('TC-008: Passwords must match', async ({ page }) => {
    await page.goto('/reset-password?token=valid-token-123');
    await page.getByLabel('New password').fill('NewSecurePass123!');
    await page.getByLabel('Confirm password').fill('DifferentPass123!');
    await page.getByRole('button', { name: 'Reset password' }).click();
    await expect(page.getByText('Passwords do not match')).toBeVisible();
  });

  // ── Negative Tests ──────────────────────────────────────────────────────

  test('TC-009: Invalid email format shows inline error', async ({ page }) => {
    await page.goto('/forgot-password');
    await page.getByLabel('Email address').fill('not-an-email');
    await page.getByRole('button', { name: 'Send reset link' }).click();
    await expect(page.getByText('Please enter a valid email address')).toBeVisible();
    // No email should be sent
    await expect(page.getByText('Reset link sent')).not.toBeVisible();
  });

  test('TC-010: Non-existent email shows generic success message (security)', async ({ page }) => {
    await page.goto('/forgot-password');
    await page.getByLabel('Email address').fill('nonexistent@example.com');
    await page.getByRole('button', { name: 'Send reset link' }).click();
    // Should show same success message to prevent email enumeration
    await expect(page.getByText('If this email exists, a reset link has been sent')).toBeVisible();
  });

  test('TC-011: Empty email field shows validation error', async ({ page }) => {
    await page.goto('/forgot-password');
    await page.getByRole('button', { name: 'Send reset link' }).click();
    await expect(page.getByText('Email address is required')).toBeVisible();
  });

  test('TC-012: Tampered token shows error', async ({ page }) => {
    await page.goto('/reset-password?token=tampered-invalid-token-xyz');
    await expect(page.getByText('Invalid reset link')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Reset password' })).not.toBeVisible();
  });

  test('TC-013: Missing token parameter shows error', async ({ page }) => {
    await page.goto('/reset-password');
    await expect(page.getByText('Invalid reset link')).toBeVisible();
  });

  test('TC-014: Rate limiting after multiple requests', async ({ page }) => {
    // Simulate 5 rapid reset requests
    for (let i = 0; i < 5; i++) {
      await page.goto('/forgot-password');
      await page.getByLabel('Email address').fill('user@example.com');
      await page.getByRole('button', { name: 'Send reset link' }).click();
    }
    await expect(page.getByText('Too many requests. Please try again later.')).toBeVisible();
  });

});
